services:
  api-nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./docker/api-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/api:/var/www/api
      - ./apps/api/.env.docker:/var/www/api/.env
    depends_on:
      php:
        condition: service_started
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
    - ./apps/api:/var/www/api
    - ./apps/api/.env.docker:/var/www/api/.env

  database:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    shm_size: 128mb
    volumes:
      - ./docker/postgresql/dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: echoo
  
  file-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/file-server/files/images:/usr/share/nginx/html/images
      - ./docker/file-server/files/musics:/usr/share/nginx/html/musics
      - ./docker/file-server/conf/nginx.conf:/etc/nginx/conf.d/default.conf