services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/api:/var/www/api
      - ./apps/api/.env.docker:/var/www/api/.env
    depends_on:
      php:
        condition: service_started
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
    - ./apps/api:/var/www/api
    - ./apps/api/.env.docker:/var/www/api/.env

  database:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/dataset:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: echoo   
  
  database_auth:
    image: postgres:18-alpine
    # build:
    #   context: .
    #   dockerfile: ./docker/postgresql/Dockerfile
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: root
    #   POSTGRES_DB: echoo_auth
    ports:
      - "5433:5432"

  auth-service:
    image: php:8.3-apache
    volumes: 
     - ./apps/auth-service-JWT/apps/api:/var/www/html
    environment:
      AUTH_SERVICE_URL: http://host.docker.internal:3333
    extra_hosts:
      # Allow accessing localhost from inside a docker container through host.docker.internal
      - "host.docker.internal:host-gateway"
    ports: 
      - 8000:80

    # build:
    #   context: .
    #   dockerfile: ./docker/auth-service/Dockerfile
    # container_name: auth-service
    # # volumes:
    # #   - ./apps/auth-service:/app
    # depends_on:
    #   - database_auth
    # tty: true
    # environment:
    #   DATABASE_URL: postgresql://postgres:root@database_auth:5432/echoo_auth
    # ports:
    #   - "3000:3000"