services:
  db:
    image: postgres:18-alpine
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - ${DB_PORT?:error}:5432
    environment:
      POSTGRES_DB: ${DB_NAME?:error}
      POSTGRES_USER: ${DB_USER?:error}
      POSTGRES_PASSWORD: ${DB_PASSWORD?:error}
    volumes: 
      - pg:/var/lib/postgresql

  php:
    image: php:8.3-apache
    volumes: 
      - ./apps/api:/var/www/html
    environment:
      AUTH_SERVICE_URL: http://host.docker.internal:${AUTH_SERVICE_PORT?:error}
    extra_hosts:
      # Allow accessing localhost from inside a docker container through host.docker.internal
      - "host.docker.internal:host-gateway"
    ports: 
      - ${API_PORT?:error}:80

volumes:
  pg: