name: API unit tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install Composer
        run: composer install --working-dir=apps/api --no-interaction --prefer-dist --optimize-autoloader

      - name: Codeception build
        run: cd apps/api && php vendor/bin/codecept build

      - name: Run PHPStan linter
        run: cd apps/api && composer lint

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install Composer
        run: composer install --working-dir=apps/api --no-interaction --prefer-dist --optimize-autoloader

      - name: Codeception build
        run: cd apps/api && php vendor/bin/codecept build

      - name: Run unit tests
        run: cd apps/api && composer unit_test

  e2e-test:
    runs-on: ubuntu-latest
    
    services:
      database:
        image: postgres:16.10-alpine3.22
        ports:
          - "5432:5432"
        volumes:
          - ./docker/postgresql/dataset:/docker-entrypoint-initdb.d
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: echoo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -v ${{ github.workspace }}/docker/postgresql/dataset:/docker-entrypoint-initdb.d

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Codeception build
        run: cd apps/api && php vendor/bin/codecept build

      - name: Run e2e tests
        run: cd apps/api && composer e2e_test
